/*
Copyright 2025 The olive Authors

This program is offered under a commercial and under the AGPL license.
For AGPL licensing, see below.

AGPL licensing:
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

syntax = "proto3";

package types;

import "tagger/tagger.proto";

option go_package = "github.com/olive-io/olive/api/types;types";
option java_multiple_files = true;
option java_package = "io.olive.api.types";
option java_outer_classname = "OliveTypes";

enum FlowNodeType {
  UnknownNode = 0;
  StartEvent = 1;
  EndEvent = 2;
  BoundaryEvent = 3;
  IntermediateCatchEvent = 4;

  Task = 11;
  SendTask = 12;
  ReceiveTask = 13;
  ServiceTask = 14;
  UserTask = 15;
  ScriptTask = 16;
  ManualTask = 17;
  CallActivity = 18;
  BusinessRuleTask = 19;
  SubProcess = 20;

  EventBasedGateway = 31;
  ExclusiveGateway = 32;
  InclusiveGateway = 33;
  ParallelGateway = 34;
}

// Definition bpmn Definition
message Definitions {
  int64 id = 1 [(tagger.tags) = "gorm:\"primary\""];

  int64 createAt = 2 [(tagger.tags) = "gorm:\"autoCreateTime\""];

  string uid = 3 [(tagger.tags) = "gorm:\"index\""];

  string description = 4;

  map<string, string> metadata = 5 [(tagger.tags) = "gorm:\"serializer:json\""];

  string content = 6;

  uint64 version = 7;

  bool isExecute = 8;
}

message BpmnArgs {
  map<string, string> headers = 1;

  map<string, bytes> properties = 2;

  map<string, bytes> dataObjects = 3;
}

enum ProcessStatus {
  UnknownStatus = 0;
  // to be 'Prepare' where Process created
  Prepare = 1;
  // to be 'Ready' where olive-server scheduled
  Ready = 2;
  Running = 3;
  Ok = 4;
  Failed = 5;
}

message Process {
  int64 id = 1 [(tagger.tags) = "gorm:\"primary\""];

  int64 createAt = 2 [(tagger.tags) = "gorm:\"autoCreateTime\""];

  string name = 3;

  map<string, string> metadata = 4 [(tagger.tags) = "gorm:\"serializer:json\""];

  int64 priority = 5;

  BpmnArgs args = 6 [(tagger.tags) = "gorm:\"serializer:json\""];

  int64 definitionsId = 7;

  uint64 definitionsVersion = 8;

  string definitionsProcess = 9;

  string definitionsContent = 10;

  ProcessContext context = 11 [(tagger.tags) = "gorm:\"serializer:json\""];

  int32 attempts = 12;

  int64 startAt = 13;

  int64 endAt = 14;

  ProcessStatus status = 15;

  string err_msg = 16;
}

message ProcessContext {
  map<string, bytes> variables = 1;

  map<string, bytes> dataObjects = 2;
}

message FlowNodeActivity {
  string id = 1 [(tagger.tags) = "gorm:\"primary\""];

  int64 createAt = 2 [(tagger.tags) = "gorm:\"autoCreateTime\""];

  string name = 3;

  FlowNodeType flow_type = 4;

  ProcessContext context = 5 [(tagger.tags) = "gorm:\"serializer:json\""];

  int32 retries = 6;

  int64 startTime = 7;

  int64 endTime = 8;

  int64 process_id = 9 [(tagger.tags) = "gorm:\"index\""];

  ProcessStatus status = 10;

  string err_msg = 11;
}
