/*
Copyright 2023 The olive Authors

This program is offered under a commercial and under the AGPL license.
For AGPL licensing, see below.

AGPL licensing:
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

syntax = "proto3";

package rpc.serverpb;

import "types/internal.proto";
import "types/bpmn.proto";
// for grpc-gateway
import "google/api/annotations.proto";

option go_package = "github.com/olive-io/olive/api/rpc/serverpb;serverpb";
option java_multiple_files = true;
option java_package = "io.olive.api.rpc.serverpb";
option java_outer_classname = "OliveRPCServerPb";

service SystemRPC {
  rpc Ping(PingRequest) returns (PingResponse) {
    option (google.api.http) = {
      get: "/v1/ping"
    };
  }
  rpc GetCluster(GetClusterRequest) returns (GetClusterResponse) {
    option (google.api.http) = {
      get: "/v1/cluster"
    };
  };
  // Register registers runner
  rpc Register(RegisterRequest) returns (RegisterResponse) {
    option (google.api.http) = {
      post: "/v1/runners/register"
      body: "*"
    };
  }
  // Disregister disregisters runner
  rpc Disregister(DisregisterRequest) returns (DisregisterResponse) {
    option (google.api.http) = {
      post: "/v1/runners/disregister"
      body: "*"
    };
  }
  // Heartbeat updates runner statistic
  rpc Heartbeat(HeartbeatRequest) returns (HeartbeatResponse) {
    option (google.api.http) = {
      post: "/v1/runners/heartbeat"
      body: "*"
    };
  }
  rpc ListRunners(ListRunnersRequest) returns (ListRunnersResponse) {
    option (google.api.http) = {
      get: "/v1/runners"
    };
  };
  rpc GetRunner(GetRunnerRequest) returns (GetRunnerResponse) {
    option (google.api.http) = {
      get: "/v1/runners/{id}"
    };
  };
}

message PingRequest {}

message PingResponse {}

message GetClusterRequest {}

message GetClusterResponse {
  types.ResponseHeader header = 1;
  types.Monitor monitor = 2;
}

message RegisterRequest {
  types.Runner runner = 1;
}

message RegisterResponse {
  types.Runner runner = 1;
}

message DisregisterRequest {
  types.Runner runner = 1;
}

message DisregisterResponse {
  types.Runner runner = 1;
}

message HeartbeatRequest {
  types.RunnerStat stat = 1;
}

message HeartbeatResponse {
  types.ResponseHeader header = 1;
}

message ListRunnersRequest {}

message ListRunnersResponse {
  repeated types.Runner runners = 1;
}

message GetRunnerRequest {
  uint64 id = 1;
}

message GetRunnerResponse {
  types.Runner runner = 1;
  types.RunnerStat stat = 2;
}

service BpmnRPC {
  rpc DeployDefinition(DeployDefinitionsRequest) returns (DeployDefinitionsResponse) {
    option (google.api.http) = {
      post: "/v1/definitions"
      body: "*"
    };
  };
  rpc ListDefinitions(ListDefinitionsRequest) returns (ListDefinitionsResponse) {
    option (google.api.http) = {
      get: "/v1/definitions"
    };
  };
  rpc GetDefinition(GetDefinitionsRequest) returns (GetDefinitionsResponse) {
    option (google.api.http) = {
      get: "/v1/definitions/{id}"
    };
  };
  rpc RemoveDefinition(RemoveDefinitionRequest) returns (RemoveDefinitionsResponse) {
    option (google.api.http) = {
      delete: "/v1/definitions/{id}"
    };
  };
  rpc ExecuteDefinition(ExecuteDefinitionRequest) returns (ExecuteDefinitionResponse) {
    option (google.api.http) = {
      post: "/v1/definitions/execute"
      body: "*"
    };
  };
  rpc ListProcess(ListProcessRequest) returns (ListProcessResponse) {
    option (google.api.http) = {
      get: "/v1/processes"
    };
  }
  rpc GetProcess(GetProcessRequest) returns (GetProcessResponse) {
    option (google.api.http) = {
      get: "/v1/processes/{id}"
    };
  }
}

message DeployDefinitionsRequest {
  types.Definitions definitions = 1;
}

message DeployDefinitionsResponse {
  types.Definitions definitions = 1;
}

message ListDefinitionsRequest {
  int32 page = 1;
  int32 size = 2;
}

message ListDefinitionsResponse {
  repeated types.Definitions definitions_list = 1;
}

message GetDefinitionsRequest {
  int64 id = 1;
  uint64 version = 2;
}

message GetDefinitionsResponse {
  types.Definitions definitions = 1;
}

message RemoveDefinitionRequest {
  int64 id = 1;
  uint64 version = 2;
}

message RemoveDefinitionsResponse {
  types.Definitions definitions = 1;
}

message ExecuteDefinitionRequest {
  string name = 1;
  int64 definitionsId = 2;
  uint64 definitionsVersion = 3;
  map<string, string> header = 4;
  map<string, bytes> properties = 5;
  map<string, bytes> dataObjects = 6;
}

message ExecuteDefinitionResponse {
  types.Process process = 1;
}

message ListProcessRequest {}

message ListProcessResponse {
  repeated types.Process processes = 1;
}

message GetProcessRequest {
  int64 id = 1;
}

message GetProcessResponse {
  types.Process process = 1;
  types.FlowNodeActivity activities = 2;
}