//
//Copyright 2023 The olive Authors
//
//This program is offered under a commercial and under the AGPL license.
//For AGPL licensing, see below.
//
//AGPL licensing:
//This program is free software: you can redistribute it and/or modify
//it under the terms of the GNU Affero General Public License as published by
//the Free Software Foundation, either version 3 of the License, or
//(at your option) any later version.
//
//This program is distributed in the hope that it will be useful,
//but WITHOUT ANY WARRANTY; without even the implied warranty of
//MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//GNU Affero General Public License for more details.
//
//You should have received a copy of the GNU Affero General Public License
//along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: github.com/olive-io/olive/api/olivepb/raft.proto

package olivepb

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InternalKV struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *InternalKV) Reset() {
	*x = InternalKV{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_olive_io_olive_api_olivepb_raft_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InternalKV) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternalKV) ProtoMessage() {}

func (x *InternalKV) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_olive_io_olive_api_olivepb_raft_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternalKV.ProtoReflect.Descriptor instead.
func (*InternalKV) Descriptor() ([]byte, []int) {
	return file_github_com_olive_io_olive_api_olivepb_raft_proto_rawDescGZIP(), []int{0}
}

func (x *InternalKV) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *InternalKV) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type KeyValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *KeyValue) Reset() {
	*x = KeyValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_olive_io_olive_api_olivepb_raft_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValue) ProtoMessage() {}

func (x *KeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_olive_io_olive_api_olivepb_raft_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValue.ProtoReflect.Descriptor instead.
func (*KeyValue) Descriptor() ([]byte, []int) {
	return file_github_com_olive_io_olive_api_olivepb_raft_proto_rawDescGZIP(), []int{1}
}

func (x *KeyValue) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *KeyValue) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type RaftHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID uint64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *RaftHeader) Reset() {
	*x = RaftHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_olive_io_olive_api_olivepb_raft_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RaftHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftHeader) ProtoMessage() {}

func (x *RaftHeader) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_olive_io_olive_api_olivepb_raft_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftHeader.ProtoReflect.Descriptor instead.
func (*RaftHeader) Descriptor() ([]byte, []int) {
	return file_github_com_olive_io_olive_api_olivepb_raft_proto_rawDescGZIP(), []int{2}
}

func (x *RaftHeader) GetID() uint64 {
	if x != nil {
		return x.ID
	}
	return 0
}

type RaftInternalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header            *RaftHeader                     `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Range             *RegionRangeRequest             `protobuf:"bytes,2,opt,name=range,proto3" json:"range,omitempty"`
	Put               *RegionPutRequest               `protobuf:"bytes,3,opt,name=put,proto3" json:"put,omitempty"`
	Delete            *RegionDeleteRequest            `protobuf:"bytes,4,opt,name=delete,proto3" json:"delete,omitempty"`
	DeployDefinition  *RegionDeployDefinitionRequest  `protobuf:"bytes,11,opt,name=deploy_definition,json=deployDefinition,proto3" json:"deploy_definition,omitempty"`
	ExecuteDefinition *RegionExecuteDefinitionRequest `protobuf:"bytes,12,opt,name=execute_definition,json=executeDefinition,proto3" json:"execute_definition,omitempty"`
}

func (x *RaftInternalRequest) Reset() {
	*x = RaftInternalRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_olive_io_olive_api_olivepb_raft_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RaftInternalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftInternalRequest) ProtoMessage() {}

func (x *RaftInternalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_olive_io_olive_api_olivepb_raft_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftInternalRequest.ProtoReflect.Descriptor instead.
func (*RaftInternalRequest) Descriptor() ([]byte, []int) {
	return file_github_com_olive_io_olive_api_olivepb_raft_proto_rawDescGZIP(), []int{3}
}

func (x *RaftInternalRequest) GetHeader() *RaftHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *RaftInternalRequest) GetRange() *RegionRangeRequest {
	if x != nil {
		return x.Range
	}
	return nil
}

func (x *RaftInternalRequest) GetPut() *RegionPutRequest {
	if x != nil {
		return x.Put
	}
	return nil
}

func (x *RaftInternalRequest) GetDelete() *RegionDeleteRequest {
	if x != nil {
		return x.Delete
	}
	return nil
}

func (x *RaftInternalRequest) GetDeployDefinition() *RegionDeployDefinitionRequest {
	if x != nil {
		return x.DeployDefinition
	}
	return nil
}

func (x *RaftInternalRequest) GetExecuteDefinition() *RegionExecuteDefinitionRequest {
	if x != nil {
		return x.ExecuteDefinition
	}
	return nil
}

type LoggablePutRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key       []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	ValueSize int64  `protobuf:"varint,2,opt,name=valueSize,proto3" json:"valueSize,omitempty"`
}

func (x *LoggablePutRequest) Reset() {
	*x = LoggablePutRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_olive_io_olive_api_olivepb_raft_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoggablePutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoggablePutRequest) ProtoMessage() {}

func (x *LoggablePutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_olive_io_olive_api_olivepb_raft_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoggablePutRequest.ProtoReflect.Descriptor instead.
func (*LoggablePutRequest) Descriptor() ([]byte, []int) {
	return file_github_com_olive_io_olive_api_olivepb_raft_proto_rawDescGZIP(), []int{4}
}

func (x *LoggablePutRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *LoggablePutRequest) GetValueSize() int64 {
	if x != nil {
		return x.ValueSize
	}
	return 0
}

type RaftResponseHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// region_id is the ID of the region which sent the response.
	RegionId uint64 `protobuf:"varint,1,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	// replica_id is the ID of the replica which sent the response.
	ReplicaId uint64 `protobuf:"varint,2,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	// raft_term is the raft term when the request was applied.
	RaftTerm uint64 `protobuf:"varint,3,opt,name=raft_term,json=raftTerm,proto3" json:"raft_term,omitempty"`
}

func (x *RaftResponseHeader) Reset() {
	*x = RaftResponseHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_olive_io_olive_api_olivepb_raft_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RaftResponseHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftResponseHeader) ProtoMessage() {}

func (x *RaftResponseHeader) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_olive_io_olive_api_olivepb_raft_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftResponseHeader.ProtoReflect.Descriptor instead.
func (*RaftResponseHeader) Descriptor() ([]byte, []int) {
	return file_github_com_olive_io_olive_api_olivepb_raft_proto_rawDescGZIP(), []int{5}
}

func (x *RaftResponseHeader) GetRegionId() uint64 {
	if x != nil {
		return x.RegionId
	}
	return 0
}

func (x *RaftResponseHeader) GetReplicaId() uint64 {
	if x != nil {
		return x.ReplicaId
	}
	return 0
}

func (x *RaftResponseHeader) GetRaftTerm() uint64 {
	if x != nil {
		return x.RaftTerm
	}
	return 0
}

type RegionRangeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key          []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	RangeEnd     []byte `protobuf:"bytes,2,opt,name=range_end,json=rangeEnd,proto3" json:"range_end,omitempty"`
	Limit        int64  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Serializable bool   `protobuf:"varint,4,opt,name=serializable,proto3" json:"serializable,omitempty"`
}

func (x *RegionRangeRequest) Reset() {
	*x = RegionRangeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_olive_io_olive_api_olivepb_raft_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegionRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionRangeRequest) ProtoMessage() {}

func (x *RegionRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_olive_io_olive_api_olivepb_raft_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionRangeRequest.ProtoReflect.Descriptor instead.
func (*RegionRangeRequest) Descriptor() ([]byte, []int) {
	return file_github_com_olive_io_olive_api_olivepb_raft_proto_rawDescGZIP(), []int{6}
}

func (x *RegionRangeRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *RegionRangeRequest) GetRangeEnd() []byte {
	if x != nil {
		return x.RangeEnd
	}
	return nil
}

func (x *RegionRangeRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *RegionRangeRequest) GetSerializable() bool {
	if x != nil {
		return x.Serializable
	}
	return false
}

type RegionRangeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *RaftResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Kvs    []*KeyValue         `protobuf:"bytes,2,rep,name=kvs,proto3" json:"kvs,omitempty"`
}

func (x *RegionRangeResponse) Reset() {
	*x = RegionRangeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_olive_io_olive_api_olivepb_raft_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegionRangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionRangeResponse) ProtoMessage() {}

func (x *RegionRangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_olive_io_olive_api_olivepb_raft_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionRangeResponse.ProtoReflect.Descriptor instead.
func (*RegionRangeResponse) Descriptor() ([]byte, []int) {
	return file_github_com_olive_io_olive_api_olivepb_raft_proto_rawDescGZIP(), []int{7}
}

func (x *RegionRangeResponse) GetHeader() *RaftResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *RegionRangeResponse) GetKvs() []*KeyValue {
	if x != nil {
		return x.Kvs
	}
	return nil
}

type RegionPutRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value  []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	IsSync bool   `protobuf:"varint,3,opt,name=is_sync,json=isSync,proto3" json:"is_sync,omitempty"`
}

func (x *RegionPutRequest) Reset() {
	*x = RegionPutRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_olive_io_olive_api_olivepb_raft_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegionPutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionPutRequest) ProtoMessage() {}

func (x *RegionPutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_olive_io_olive_api_olivepb_raft_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionPutRequest.ProtoReflect.Descriptor instead.
func (*RegionPutRequest) Descriptor() ([]byte, []int) {
	return file_github_com_olive_io_olive_api_olivepb_raft_proto_rawDescGZIP(), []int{8}
}

func (x *RegionPutRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *RegionPutRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *RegionPutRequest) GetIsSync() bool {
	if x != nil {
		return x.IsSync
	}
	return false
}

type RegionPutResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *RaftResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	PreKv  *KeyValue           `protobuf:"bytes,2,opt,name=preKv,proto3" json:"preKv,omitempty"`
}

func (x *RegionPutResponse) Reset() {
	*x = RegionPutResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_olive_io_olive_api_olivepb_raft_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegionPutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionPutResponse) ProtoMessage() {}

func (x *RegionPutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_olive_io_olive_api_olivepb_raft_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionPutResponse.ProtoReflect.Descriptor instead.
func (*RegionPutResponse) Descriptor() ([]byte, []int) {
	return file_github_com_olive_io_olive_api_olivepb_raft_proto_rawDescGZIP(), []int{9}
}

func (x *RegionPutResponse) GetHeader() *RaftResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *RegionPutResponse) GetPreKv() *KeyValue {
	if x != nil {
		return x.PreKv
	}
	return nil
}

type RegionDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	IsSync bool   `protobuf:"varint,2,opt,name=is_sync,json=isSync,proto3" json:"is_sync,omitempty"`
}

func (x *RegionDeleteRequest) Reset() {
	*x = RegionDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_olive_io_olive_api_olivepb_raft_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegionDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionDeleteRequest) ProtoMessage() {}

func (x *RegionDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_olive_io_olive_api_olivepb_raft_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionDeleteRequest.ProtoReflect.Descriptor instead.
func (*RegionDeleteRequest) Descriptor() ([]byte, []int) {
	return file_github_com_olive_io_olive_api_olivepb_raft_proto_rawDescGZIP(), []int{10}
}

func (x *RegionDeleteRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *RegionDeleteRequest) GetIsSync() bool {
	if x != nil {
		return x.IsSync
	}
	return false
}

type RegionDeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *RaftResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	PreKv  *KeyValue           `protobuf:"bytes,2,opt,name=preKv,proto3" json:"preKv,omitempty"`
}

func (x *RegionDeleteResponse) Reset() {
	*x = RegionDeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_olive_io_olive_api_olivepb_raft_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegionDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionDeleteResponse) ProtoMessage() {}

func (x *RegionDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_olive_io_olive_api_olivepb_raft_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionDeleteResponse.ProtoReflect.Descriptor instead.
func (*RegionDeleteResponse) Descriptor() ([]byte, []int) {
	return file_github_com_olive_io_olive_api_olivepb_raft_proto_rawDescGZIP(), []int{11}
}

func (x *RegionDeleteResponse) GetHeader() *RaftResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *RegionDeleteResponse) GetPreKv() *KeyValue {
	if x != nil {
		return x.PreKv
	}
	return nil
}

type RegionDeployDefinitionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Definition *Definition `protobuf:"bytes,1,opt,name=definition,proto3" json:"definition,omitempty"`
}

func (x *RegionDeployDefinitionRequest) Reset() {
	*x = RegionDeployDefinitionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_olive_io_olive_api_olivepb_raft_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegionDeployDefinitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionDeployDefinitionRequest) ProtoMessage() {}

func (x *RegionDeployDefinitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_olive_io_olive_api_olivepb_raft_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionDeployDefinitionRequest.ProtoReflect.Descriptor instead.
func (*RegionDeployDefinitionRequest) Descriptor() ([]byte, []int) {
	return file_github_com_olive_io_olive_api_olivepb_raft_proto_rawDescGZIP(), []int{12}
}

func (x *RegionDeployDefinitionRequest) GetDefinition() *Definition {
	if x != nil {
		return x.Definition
	}
	return nil
}

type RegionDeployDefinitionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header     *RaftResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Definition *Definition         `protobuf:"bytes,2,opt,name=definition,proto3" json:"definition,omitempty"`
}

func (x *RegionDeployDefinitionResponse) Reset() {
	*x = RegionDeployDefinitionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_olive_io_olive_api_olivepb_raft_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegionDeployDefinitionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionDeployDefinitionResponse) ProtoMessage() {}

func (x *RegionDeployDefinitionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_olive_io_olive_api_olivepb_raft_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionDeployDefinitionResponse.ProtoReflect.Descriptor instead.
func (*RegionDeployDefinitionResponse) Descriptor() ([]byte, []int) {
	return file_github_com_olive_io_olive_api_olivepb_raft_proto_rawDescGZIP(), []int{13}
}

func (x *RegionDeployDefinitionResponse) GetHeader() *RaftResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *RegionDeployDefinitionResponse) GetDefinition() *Definition {
	if x != nil {
		return x.Definition
	}
	return nil
}

type RegionExecuteDefinitionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProcessInstance *ProcessInstance `protobuf:"bytes,1,opt,name=process_instance,json=processInstance,proto3" json:"process_instance,omitempty"`
}

func (x *RegionExecuteDefinitionRequest) Reset() {
	*x = RegionExecuteDefinitionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_olive_io_olive_api_olivepb_raft_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegionExecuteDefinitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionExecuteDefinitionRequest) ProtoMessage() {}

func (x *RegionExecuteDefinitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_olive_io_olive_api_olivepb_raft_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionExecuteDefinitionRequest.ProtoReflect.Descriptor instead.
func (*RegionExecuteDefinitionRequest) Descriptor() ([]byte, []int) {
	return file_github_com_olive_io_olive_api_olivepb_raft_proto_rawDescGZIP(), []int{14}
}

func (x *RegionExecuteDefinitionRequest) GetProcessInstance() *ProcessInstance {
	if x != nil {
		return x.ProcessInstance
	}
	return nil
}

type RegionExecuteDefinitionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header          *RaftResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	ProcessInstance *ProcessInstance    `protobuf:"bytes,2,opt,name=process_instance,json=processInstance,proto3" json:"process_instance,omitempty"`
}

func (x *RegionExecuteDefinitionResponse) Reset() {
	*x = RegionExecuteDefinitionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_olive_io_olive_api_olivepb_raft_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegionExecuteDefinitionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionExecuteDefinitionResponse) ProtoMessage() {}

func (x *RegionExecuteDefinitionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_olive_io_olive_api_olivepb_raft_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionExecuteDefinitionResponse.ProtoReflect.Descriptor instead.
func (*RegionExecuteDefinitionResponse) Descriptor() ([]byte, []int) {
	return file_github_com_olive_io_olive_api_olivepb_raft_proto_rawDescGZIP(), []int{15}
}

func (x *RegionExecuteDefinitionResponse) GetHeader() *RaftResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *RegionExecuteDefinitionResponse) GetProcessInstance() *ProcessInstance {
	if x != nil {
		return x.ProcessInstance
	}
	return nil
}

var File_github_com_olive_io_olive_api_olivepb_raft_proto protoreflect.FileDescriptor

var file_github_com_olive_io_olive_api_olivepb_raft_proto_rawDesc = []byte{
	0x0a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x6c, 0x69,
	0x76, 0x65, 0x2d, 0x69, 0x6f, 0x2f, 0x6f, 0x6c, 0x69, 0x76, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x6f, 0x6c, 0x69, 0x76, 0x65, 0x70, 0x62, 0x2f, 0x72, 0x61, 0x66, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x07, 0x6f, 0x6c, 0x69, 0x76, 0x65, 0x70, 0x62, 0x1a, 0x34, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x6c, 0x69, 0x76, 0x65, 0x2d, 0x69, 0x6f,
	0x2f, 0x6f, 0x6c, 0x69, 0x76, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6f, 0x6c, 0x69, 0x76, 0x65,
	0x70, 0x62, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x34, 0x0a, 0x0a, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x4b, 0x56, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x32, 0x0a, 0x08, 0x4b, 0x65, 0x79, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x1c, 0x0a, 0x0a, 0x52,
	0x61, 0x66, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x49, 0x44, 0x22, 0x85, 0x03, 0x0a, 0x13, 0x52, 0x61,
	0x66, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x2b, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x6f, 0x6c, 0x69, 0x76, 0x65, 0x70, 0x62, 0x2e, 0x52, 0x61, 0x66, 0x74,
	0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x31,
	0x0a, 0x05, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e,
	0x6f, 0x6c, 0x69, 0x76, 0x65, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x52, 0x61,
	0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x05, 0x72, 0x61, 0x6e, 0x67,
	0x65, 0x12, 0x2b, 0x0a, 0x03, 0x70, 0x75, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19,
	0x2e, 0x6f, 0x6c, 0x69, 0x76, 0x65, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x50,
	0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x03, 0x70, 0x75, 0x74, 0x12, 0x34,
	0x0a, 0x06, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c,
	0x2e, 0x6f, 0x6c, 0x69, 0x76, 0x65, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x06, 0x64, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x12, 0x53, 0x0a, 0x11, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x5f, 0x64,
	0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x26, 0x2e, 0x6f, 0x6c, 0x69, 0x76, 0x65, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e,
	0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x10, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x44,
	0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x56, 0x0a, 0x12, 0x65, 0x78, 0x65,
	0x63, 0x75, 0x74, 0x65, 0x5f, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x6f, 0x6c, 0x69, 0x76, 0x65, 0x70, 0x62, 0x2e,
	0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x44, 0x65, 0x66,
	0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x11,
	0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x22, 0x44, 0x0a, 0x12, 0x4c, 0x6f, 0x67, 0x67, 0x61, 0x62, 0x6c, 0x65, 0x50, 0x75, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x6d, 0x0a, 0x12, 0x52, 0x61, 0x66, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x1b, 0x0a,
	0x09, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x08, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65,
	0x70, 0x6c, 0x69, 0x63, 0x61, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09,
	0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x61, 0x66,
	0x74, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x72, 0x61,
	0x66, 0x74, 0x54, 0x65, 0x72, 0x6d, 0x22, 0x7d, 0x0a, 0x12, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e,
	0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x1b,
	0x0a, 0x09, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x65, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x08, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x45, 0x6e, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x12, 0x22, 0x0a, 0x0c, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x62, 0x6c,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69,
	0x7a, 0x61, 0x62, 0x6c, 0x65, 0x22, 0x6f, 0x0a, 0x13, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x52,
	0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x06,
	0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6f,
	0x6c, 0x69, 0x76, 0x65, 0x70, 0x62, 0x2e, 0x52, 0x61, 0x66, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x12, 0x23, 0x0a, 0x03, 0x6b, 0x76, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x6f, 0x6c, 0x69, 0x76, 0x65, 0x70, 0x62, 0x2e, 0x4b, 0x65, 0x79, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x52, 0x03, 0x6b, 0x76, 0x73, 0x22, 0x53, 0x0a, 0x10, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e,
	0x50, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x73, 0x5f, 0x73, 0x79, 0x6e, 0x63, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x73, 0x53, 0x79, 0x6e, 0x63, 0x22, 0x71, 0x0a, 0x11, 0x52,
	0x65, 0x67, 0x69, 0x6f, 0x6e, 0x50, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x33, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x6f, 0x6c, 0x69, 0x76, 0x65, 0x70, 0x62, 0x2e, 0x52, 0x61, 0x66, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x27, 0x0a, 0x05, 0x70, 0x72, 0x65, 0x4b, 0x76, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6f, 0x6c, 0x69, 0x76, 0x65, 0x70, 0x62, 0x2e, 0x4b,
	0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x70, 0x72, 0x65, 0x4b, 0x76, 0x22, 0x40,
	0x0a, 0x13, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x73, 0x5f, 0x73, 0x79,
	0x6e, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x73, 0x53, 0x79, 0x6e, 0x63,
	0x22, 0x74, 0x0a, 0x14, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6f, 0x6c, 0x69, 0x76, 0x65,
	0x70, 0x62, 0x2e, 0x52, 0x61, 0x66, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x27, 0x0a,
	0x05, 0x70, 0x72, 0x65, 0x4b, 0x76, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6f,
	0x6c, 0x69, 0x76, 0x65, 0x70, 0x62, 0x2e, 0x4b, 0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52,
	0x05, 0x70, 0x72, 0x65, 0x4b, 0x76, 0x22, 0x54, 0x0a, 0x1d, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e,
	0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x33, 0x0a, 0x0a, 0x64, 0x65, 0x66, 0x69, 0x6e,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6f, 0x6c,
	0x69, 0x76, 0x65, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x0a, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x8a, 0x01, 0x0a,
	0x1e, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x44, 0x65, 0x66,
	0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x33, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1b, 0x2e, 0x6f, 0x6c, 0x69, 0x76, 0x65, 0x70, 0x62, 0x2e, 0x52, 0x61, 0x66, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x12, 0x33, 0x0a, 0x0a, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6f, 0x6c, 0x69, 0x76, 0x65,
	0x70, 0x62, 0x2e, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x64,
	0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x65, 0x0a, 0x1e, 0x52, 0x65, 0x67,
	0x69, 0x6f, 0x6e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x43, 0x0a, 0x10, 0x70,
	0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6f, 0x6c, 0x69, 0x76, 0x65, 0x70, 0x62, 0x2e,
	0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52,
	0x0f, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65,
	0x22, 0x9b, 0x01, 0x0a, 0x1f, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x45, 0x78, 0x65, 0x63, 0x75,
	0x74, 0x65, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6f, 0x6c, 0x69, 0x76, 0x65, 0x70, 0x62, 0x2e, 0x52,
	0x61, 0x66, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x43, 0x0a, 0x10, 0x70, 0x72, 0x6f,
	0x63, 0x65, 0x73, 0x73, 0x5f, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6f, 0x6c, 0x69, 0x76, 0x65, 0x70, 0x62, 0x2e, 0x50, 0x72,
	0x6f, 0x63, 0x65, 0x73, 0x73, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x0f, 0x70,
	0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x42, 0x2f,
	0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x6c, 0x69,
	0x76, 0x65, 0x2d, 0x69, 0x6f, 0x2f, 0x6f, 0x6c, 0x69, 0x76, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x6f, 0x6c, 0x69, 0x76, 0x65, 0x70, 0x62, 0x3b, 0x6f, 0x6c, 0x69, 0x76, 0x65, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_github_com_olive_io_olive_api_olivepb_raft_proto_rawDescOnce sync.Once
	file_github_com_olive_io_olive_api_olivepb_raft_proto_rawDescData = file_github_com_olive_io_olive_api_olivepb_raft_proto_rawDesc
)

func file_github_com_olive_io_olive_api_olivepb_raft_proto_rawDescGZIP() []byte {
	file_github_com_olive_io_olive_api_olivepb_raft_proto_rawDescOnce.Do(func() {
		file_github_com_olive_io_olive_api_olivepb_raft_proto_rawDescData = protoimpl.X.CompressGZIP(file_github_com_olive_io_olive_api_olivepb_raft_proto_rawDescData)
	})
	return file_github_com_olive_io_olive_api_olivepb_raft_proto_rawDescData
}

var file_github_com_olive_io_olive_api_olivepb_raft_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_github_com_olive_io_olive_api_olivepb_raft_proto_goTypes = []interface{}{
	(*InternalKV)(nil),                      // 0: olivepb.InternalKV
	(*KeyValue)(nil),                        // 1: olivepb.KeyValue
	(*RaftHeader)(nil),                      // 2: olivepb.RaftHeader
	(*RaftInternalRequest)(nil),             // 3: olivepb.RaftInternalRequest
	(*LoggablePutRequest)(nil),              // 4: olivepb.LoggablePutRequest
	(*RaftResponseHeader)(nil),              // 5: olivepb.RaftResponseHeader
	(*RegionRangeRequest)(nil),              // 6: olivepb.RegionRangeRequest
	(*RegionRangeResponse)(nil),             // 7: olivepb.RegionRangeResponse
	(*RegionPutRequest)(nil),                // 8: olivepb.RegionPutRequest
	(*RegionPutResponse)(nil),               // 9: olivepb.RegionPutResponse
	(*RegionDeleteRequest)(nil),             // 10: olivepb.RegionDeleteRequest
	(*RegionDeleteResponse)(nil),            // 11: olivepb.RegionDeleteResponse
	(*RegionDeployDefinitionRequest)(nil),   // 12: olivepb.RegionDeployDefinitionRequest
	(*RegionDeployDefinitionResponse)(nil),  // 13: olivepb.RegionDeployDefinitionResponse
	(*RegionExecuteDefinitionRequest)(nil),  // 14: olivepb.RegionExecuteDefinitionRequest
	(*RegionExecuteDefinitionResponse)(nil), // 15: olivepb.RegionExecuteDefinitionResponse
	(*Definition)(nil),                      // 16: olivepb.Definition
	(*ProcessInstance)(nil),                 // 17: olivepb.ProcessInstance
}
var file_github_com_olive_io_olive_api_olivepb_raft_proto_depIdxs = []int32{
	2,  // 0: olivepb.RaftInternalRequest.header:type_name -> olivepb.RaftHeader
	6,  // 1: olivepb.RaftInternalRequest.range:type_name -> olivepb.RegionRangeRequest
	8,  // 2: olivepb.RaftInternalRequest.put:type_name -> olivepb.RegionPutRequest
	10, // 3: olivepb.RaftInternalRequest.delete:type_name -> olivepb.RegionDeleteRequest
	12, // 4: olivepb.RaftInternalRequest.deploy_definition:type_name -> olivepb.RegionDeployDefinitionRequest
	14, // 5: olivepb.RaftInternalRequest.execute_definition:type_name -> olivepb.RegionExecuteDefinitionRequest
	5,  // 6: olivepb.RegionRangeResponse.header:type_name -> olivepb.RaftResponseHeader
	1,  // 7: olivepb.RegionRangeResponse.kvs:type_name -> olivepb.KeyValue
	5,  // 8: olivepb.RegionPutResponse.header:type_name -> olivepb.RaftResponseHeader
	1,  // 9: olivepb.RegionPutResponse.preKv:type_name -> olivepb.KeyValue
	5,  // 10: olivepb.RegionDeleteResponse.header:type_name -> olivepb.RaftResponseHeader
	1,  // 11: olivepb.RegionDeleteResponse.preKv:type_name -> olivepb.KeyValue
	16, // 12: olivepb.RegionDeployDefinitionRequest.definition:type_name -> olivepb.Definition
	5,  // 13: olivepb.RegionDeployDefinitionResponse.header:type_name -> olivepb.RaftResponseHeader
	16, // 14: olivepb.RegionDeployDefinitionResponse.definition:type_name -> olivepb.Definition
	17, // 15: olivepb.RegionExecuteDefinitionRequest.process_instance:type_name -> olivepb.ProcessInstance
	5,  // 16: olivepb.RegionExecuteDefinitionResponse.header:type_name -> olivepb.RaftResponseHeader
	17, // 17: olivepb.RegionExecuteDefinitionResponse.process_instance:type_name -> olivepb.ProcessInstance
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_github_com_olive_io_olive_api_olivepb_raft_proto_init() }
func file_github_com_olive_io_olive_api_olivepb_raft_proto_init() {
	if File_github_com_olive_io_olive_api_olivepb_raft_proto != nil {
		return
	}
	file_github_com_olive_io_olive_api_olivepb_internal_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_github_com_olive_io_olive_api_olivepb_raft_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InternalKV); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_olive_io_olive_api_olivepb_raft_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_olive_io_olive_api_olivepb_raft_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RaftHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_olive_io_olive_api_olivepb_raft_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RaftInternalRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_olive_io_olive_api_olivepb_raft_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoggablePutRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_olive_io_olive_api_olivepb_raft_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RaftResponseHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_olive_io_olive_api_olivepb_raft_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegionRangeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_olive_io_olive_api_olivepb_raft_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegionRangeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_olive_io_olive_api_olivepb_raft_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegionPutRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_olive_io_olive_api_olivepb_raft_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegionPutResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_olive_io_olive_api_olivepb_raft_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegionDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_olive_io_olive_api_olivepb_raft_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegionDeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_olive_io_olive_api_olivepb_raft_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegionDeployDefinitionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_olive_io_olive_api_olivepb_raft_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegionDeployDefinitionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_olive_io_olive_api_olivepb_raft_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegionExecuteDefinitionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_olive_io_olive_api_olivepb_raft_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegionExecuteDefinitionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_github_com_olive_io_olive_api_olivepb_raft_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_olive_io_olive_api_olivepb_raft_proto_goTypes,
		DependencyIndexes: file_github_com_olive_io_olive_api_olivepb_raft_proto_depIdxs,
		MessageInfos:      file_github_com_olive_io_olive_api_olivepb_raft_proto_msgTypes,
	}.Build()
	File_github_com_olive_io_olive_api_olivepb_raft_proto = out.File
	file_github_com_olive_io_olive_api_olivepb_raft_proto_rawDesc = nil
	file_github_com_olive_io_olive_api_olivepb_raft_proto_goTypes = nil
	file_github_com_olive_io_olive_api_olivepb_raft_proto_depIdxs = nil
}
