//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Copyright 2024 lack
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// Code generated by deepcopy-gen. Do NOT EDIT.

package meta

import (
	"github.com/olive-io/olive/api"
)

// DeepCopyInto is an auto-generated deepcopy function, coping the receiver, writing into out. in must be no-nil.
func (in *Custom) DeepCopyInto(out *Custom) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	return
}

// DeepCopy is an auto-generated deepcopy function, copying the receiver, creating a new Custom.
func (in *Custom) DeepCopy() *Custom {
	if in == nil {
		return nil
	}
	out := new(Custom)
	in.DeepCopyInto(out)
	return out
}

// DeepFrom is an auto-generated deepcopy function, copying from Custom.
func (in *Custom) DeepFrom(o *Custom) {
	if in == nil {
		return
	}
	o.DeepCopyInto(in)
}

// DeepCopyObject is an auto-generated deepcopy function, copying the receiver, creating a new Custom.
func (in *Custom) DeepCopyObject() api.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepFromObject is an auto-generated deepcopy function, copying from Custom.
func (in *Custom) DeepFromObject(o api.Object) {
	if v, ok := o.(*Custom); ok {
		in.DeepFrom(v)
	}
}

// DeepCopyInto is an auto-generated deepcopy function, coping the receiver, writing into out. in must be no-nil.
func (in *ObjectMeta) DeepCopyInto(out *ObjectMeta) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an auto-generated deepcopy function, copying the receiver, creating a new ObjectMeta.
func (in *ObjectMeta) DeepCopy() *ObjectMeta {
	if in == nil {
		return nil
	}
	out := new(ObjectMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepFrom is an auto-generated deepcopy function, copying from ObjectMeta.
func (in *ObjectMeta) DeepFrom(o *ObjectMeta) {
	if in == nil {
		return
	}
	o.DeepCopyInto(in)
}

// DeepCopyInto is an auto-generated deepcopy function, coping the receiver, writing into out. in must be no-nil.
func (in *TypeMeta) DeepCopyInto(out *TypeMeta) {
	*out = *in
	return
}

// DeepCopy is an auto-generated deepcopy function, copying the receiver, creating a new TypeMeta.
func (in *TypeMeta) DeepCopy() *TypeMeta {
	if in == nil {
		return nil
	}
	out := new(TypeMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepFrom is an auto-generated deepcopy function, copying from TypeMeta.
func (in *TypeMeta) DeepFrom(o *TypeMeta) {
	if in == nil {
		return
	}
	o.DeepCopyInto(in)
}
